import type { Lang } from './utils';

export type FooterCopy = {
	colEvent: string;
	colOrg: string;
	colMedia: string;
	colContact: string;
	linkAbout: string;
	linkInstructors: string;
	linkRegistration: string;
	linkProgram: string;
	linkFoundation: string;
	linkPartners: string;
	linkMedia: string;
	linkNews: string;
	linkGallery: string;
	linkContact: string;
	legalLabel: string;
	dateLocation: string;
	copyright: string;
};

export const footerCopyByLang: Record<Lang, FooterCopy> = {
	pl: { colEvent: 'WYDARZENIE', colOrg: 'ORGANIZACJA', colMedia: 'MEDIA I PARTNERZY', colContact: 'KONTAKT', linkAbout: 'O Wydarzeniu', linkInstructors: 'Instruktorzy', linkRegistration: 'Rejestracja', linkProgram: 'Program', linkFoundation: 'Fundacja PACTA K9', linkPartners: 'Partnerzy', linkMedia: 'Media', linkNews: 'Aktualności', linkGallery: 'Galeria', linkContact: 'Kontakt', legalLabel: 'DANE REJESTROWE', dateLocation: '13–14 CZERWCA 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Wszelkie prawa zastrzeżone · Sebastian Bożek.' },
	en: { colEvent: 'EVENT', colOrg: 'ORGANIZATION', colMedia: 'MEDIA & PARTNERS', colContact: 'CONTACT', linkAbout: 'About the Event', linkInstructors: 'Instructors', linkRegistration: 'Registration', linkProgram: 'Program', linkFoundation: 'PACTA K9 Foundation', linkPartners: 'Partners', linkMedia: 'Media', linkNews: 'News', linkGallery: 'Gallery', linkContact: 'Contact', legalLabel: 'REGISTRY DATA', dateLocation: '13–14 JUNE 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. All rights reserved · Sebastian Bożek.' },
	de: { colEvent: 'VERANSTALTUNG', colOrg: 'ORGANISATION', colMedia: 'MEDIEN & PARTNER', colContact: 'KONTAKT', linkAbout: 'Über die Veranstaltung', linkInstructors: 'Instrukteure', linkRegistration: 'Anmeldung', linkProgram: 'Programm', linkFoundation: 'PACTA K9 Stiftung', linkPartners: 'Partner', linkMedia: 'Medien', linkNews: 'Aktuelles', linkGallery: 'Galerie', linkContact: 'Kontakt', legalLabel: 'REGISTERDATEN', dateLocation: '13.–14. JUNI 2026 · DANZIG', copyright: 'CERBERUS K9 © 2026. Alle Rechte vorbehalten · Sebastian Bożek.' },
	fr: { colEvent: 'ÉVÉNEMENT', colOrg: 'ORGANISATION', colMedia: 'MÉDIAS & PARTENAIRES', colContact: 'CONTACT', linkAbout: "À propos de l'événement", linkInstructors: 'Instructeurs', linkRegistration: 'Inscription', linkProgram: 'Programme', linkFoundation: 'Fondation PACTA K9', linkPartners: 'Partenaires', linkMedia: 'Médias', linkNews: 'Actualités', linkGallery: 'Galerie', linkContact: 'Contact', legalLabel: "DONNÉES D'ENREGISTREMENT", dateLocation: '13–14 JUIN 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Tous droits réservés · Sebastian Bożek.' },
	hr: { colEvent: 'DOGAĐAJ', colOrg: 'ORGANIZACIJA', colMedia: 'MEDIJI I PARTNERI', colContact: 'KONTAKT', linkAbout: 'O događaju', linkInstructors: 'Instruktori', linkRegistration: 'Registracija', linkProgram: 'Program', linkFoundation: 'Zaklada PACTA K9', linkPartners: 'Partneri', linkMedia: 'Mediji', linkNews: 'Vijesti', linkGallery: 'Galerija', linkContact: 'Kontakt', legalLabel: 'REGISTARSKI PODACI', dateLocation: '13.–14. LIPNJA 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Sva prava pridržana · Sebastian Bożek.' },
	cs: { colEvent: 'UDÁLOST', colOrg: 'ORGANIZACE', colMedia: 'MÉDIA A PARTNEŘI', colContact: 'KONTAKT', linkAbout: 'O události', linkInstructors: 'Instruktoři', linkRegistration: 'Registrace', linkProgram: 'Program', linkFoundation: 'Nadace PACTA K9', linkPartners: 'Partneři', linkMedia: 'Média', linkNews: 'Aktuality', linkGallery: 'Galerie', linkContact: 'Kontakt', legalLabel: 'REGISTRAČNÍ ÚDAJE', dateLocation: '13.–14. ČERVNA 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Všechna práva vyhrazena · Sebastian Bożek.' },
	lt: { colEvent: 'RENGINYS', colOrg: 'ORGANIZACIJA', colMedia: 'ŽINIASKLAIDA IR PARTNERIAI', colContact: 'KONTAKTAI', linkAbout: 'Apie renginį', linkInstructors: 'Instruktoriai', linkRegistration: 'Registracija', linkProgram: 'Programa', linkFoundation: 'PACTA K9 fondas', linkPartners: 'Partneriai', linkMedia: 'Žiniasklaida', linkNews: 'Naujienos', linkGallery: 'Galerija', linkContact: 'Kontaktai', legalLabel: 'REGISTRO DUOMENYS', dateLocation: '2026 M. BIRŽELIO 13–14 D. · GDAŃSKAS', copyright: 'CERBERUS K9 © 2026. Visos teisės saugomos · Sebastian Bożek.' },
	lv: { colEvent: 'PASĀKUMS', colOrg: 'ORGANIZĀCIJA', colMedia: 'MEDIJI UN PARTNERI', colContact: 'KONTAKTI', linkAbout: 'Par pasākumu', linkInstructors: 'Instruktori', linkRegistration: 'Reģistrācija', linkProgram: 'Programma', linkFoundation: 'PACTA K9 fonds', linkPartners: 'Partneri', linkMedia: 'Mediji', linkNews: 'Jaunumi', linkGallery: 'Galerija', linkContact: 'Kontakti', legalLabel: 'REĢISTRA DATI', dateLocation: '13.–14. JŪNIJS 2026 · GDAŅSKA', copyright: 'CERBERUS K9 © 2026. Visas tiesības aizsargātas · Sebastian Bożek.' },
	sk: { colEvent: 'PODUJATIE', colOrg: 'ORGANIZÁCIA', colMedia: 'MÉDIÁ A PARTNERI', colContact: 'KONTAKT', linkAbout: 'O podujatí', linkInstructors: 'Inštruktori', linkRegistration: 'Registrácia', linkProgram: 'Program', linkFoundation: 'Nadácia PACTA K9', linkPartners: 'Partneri', linkMedia: 'Médiá', linkNews: 'Aktuality', linkGallery: 'Galéria', linkContact: 'Kontakt', legalLabel: 'REGISTRAČNÉ ÚDAJE', dateLocation: '13.–14. JÚNA 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Všetky práva vyhradené · Sebastian Bożek.' },
	sl: { colEvent: 'DOGODEK', colOrg: 'ORGANIZACIJA', colMedia: 'MEDIJI IN PARTNERJI', colContact: 'KONTAKT', linkAbout: 'O dogodku', linkInstructors: 'Inštruktorji', linkRegistration: 'Registracija', linkProgram: 'Program', linkFoundation: 'Fundacija PACTA K9', linkPartners: 'Partnerji', linkMedia: 'Mediji', linkNews: 'Novosti', linkGallery: 'Galerija', linkContact: 'Kontakt', legalLabel: 'REGISTRSKI PODATKI', dateLocation: '13.–14. JUNIJ 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Vse pravice pridržane · Sebastian Bożek.' },
	hu: { colEvent: 'ESEMÉNY', colOrg: 'SZERVEZET', colMedia: 'MÉDIA ÉS PARTNEREK', colContact: 'KAPCSOLAT', linkAbout: 'Az eseményről', linkInstructors: 'Oktatók', linkRegistration: 'Regisztráció', linkProgram: 'Program', linkFoundation: 'PACTA K9 Alapítvány', linkPartners: 'Partnerek', linkMedia: 'Média', linkNews: 'Hírek', linkGallery: 'Galéria', linkContact: 'Kapcsolat', legalLabel: 'NYILVÁNTARTÁSI ADATOK', dateLocation: '2026. JÚNIUS 13–14. · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Minden jog fenntartva · Sebastian Bożek.' },
	no: { colEvent: 'ARRANGEMENT', colOrg: 'ORGANISASJON', colMedia: 'MEDIA OG PARTNERE', colContact: 'KONTAKT', linkAbout: 'Om arrangementet', linkInstructors: 'Instruktører', linkRegistration: 'Registrering', linkProgram: 'Program', linkFoundation: 'PACTA K9-stiftelsen', linkPartners: 'Partnere', linkMedia: 'Media', linkNews: 'Nyheter', linkGallery: 'Galleri', linkContact: 'Kontakt', legalLabel: 'REGISTERDATA', dateLocation: '13.–14. JUNI 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Alle rettigheter forbeholdt · Sebastian Bożek.' },
	sv: { colEvent: 'EVENEMANG', colOrg: 'ORGANISATION', colMedia: 'MEDIA OCH PARTNERS', colContact: 'KONTAKT', linkAbout: 'Om evenemanget', linkInstructors: 'Instruktörer', linkRegistration: 'Registrering', linkProgram: 'Program', linkFoundation: 'PACTA K9-stiftelsen', linkPartners: 'Partners', linkMedia: 'Media', linkNews: 'Nyheter', linkGallery: 'Galleri', linkContact: 'Kontakt', legalLabel: 'REGISTRERINGSUPPGIFTER', dateLocation: '13–14 JUNI 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Alla rättigheter förbehållna · Sebastian Bożek.' },
	nl: { colEvent: 'EVENEMENT', colOrg: 'ORGANISATIE', colMedia: 'MEDIA EN PARTNERS', colContact: 'CONTACT', linkAbout: 'Over het evenement', linkInstructors: 'Instructeurs', linkRegistration: 'Registratie', linkProgram: 'Programma', linkFoundation: 'PACTA K9 Stichting', linkPartners: 'Partners', linkMedia: 'Media', linkNews: 'Nieuws', linkGallery: 'Galerij', linkContact: 'Contact', legalLabel: 'REGISTERGEGEVENS', dateLocation: '13–14 JUNI 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Alle rechten voorbehouden · Sebastian Bożek.' },
	es: { colEvent: 'EVENTO', colOrg: 'ORGANIZACIÓN', colMedia: 'MEDIOS Y SOCIOS', colContact: 'CONTACTO', linkAbout: 'Sobre el evento', linkInstructors: 'Instructores', linkRegistration: 'Registro', linkProgram: 'Programa', linkFoundation: 'Fundación PACTA K9', linkPartners: 'Socios', linkMedia: 'Medios', linkNews: 'Noticias', linkGallery: 'Galería', linkContact: 'Contacto', legalLabel: 'DATOS REGISTRALES', dateLocation: '13–14 DE JUNIO DE 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Todos los derechos reservados · Sebastian Bożek.' },
	pt: { colEvent: 'EVENTO', colOrg: 'ORGANIZAÇÃO', colMedia: 'MEDIA E PARCEIROS', colContact: 'CONTACTO', linkAbout: 'Sobre o evento', linkInstructors: 'Instrutores', linkRegistration: 'Registo', linkProgram: 'Programa', linkFoundation: 'Fundação PACTA K9', linkPartners: 'Parceiros', linkMedia: 'Media', linkNews: 'Notícias', linkGallery: 'Galeria', linkContact: 'Contacto', legalLabel: 'DADOS DE REGISTO', dateLocation: '13–14 DE JUNHO DE 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Todos os direitos reservados · Sebastian Bożek.' },
	ro: { colEvent: 'EVENIMENT', colOrg: 'ORGANIZAȚIE', colMedia: 'MEDIA ȘI PARTENERI', colContact: 'CONTACT', linkAbout: 'Despre eveniment', linkInstructors: 'Instructori', linkRegistration: 'Înregistrare', linkProgram: 'Program', linkFoundation: 'Fundația PACTA K9', linkPartners: 'Parteneri', linkMedia: 'Media', linkNews: 'Știri', linkGallery: 'Galerie', linkContact: 'Contact', legalLabel: 'DATE DE ÎNREGISTRARE', dateLocation: '13–14 IUNIE 2026 · GDAŃSK', copyright: 'CERBERUS K9 © 2026. Toate drepturile rezervate · Sebastian Bożek.' },
	it: { colEvent: 'EVENTO', colOrg: 'ORGANIZZAZIONE', colMedia: 'MEDIA E PARTNER', colContact: 'CONTATTO', linkAbout: "Sull'evento", linkInstructors: 'Istruttori', linkRegistration: 'Registrazione', linkProgram: 'Programma', linkFoundation: 'Fondazione PACTA K9', linkPartners: 'Partner', linkMedia: 'Media', linkNews: 'Notizie', linkGallery: 'Galleria', linkContact: 'Contatto', legalLabel: 'DATI DI REGISTRAZIONE', dateLocation: '13–14 GIUGNO 2026 · DÀNICA', copyright: 'CERBERUS K9 © 2026. Tutti i diritti riservati · Sebastian Bożek.' },
	ko: { colEvent: '행사', colOrg: '조직', colMedia: '미디어 및 파트너', colContact: '문의', linkAbout: '행사 소개', linkInstructors: '강사진', linkRegistration: '등록', linkProgram: '프로그램', linkFoundation: 'PACTA K9 재단', linkPartners: '파트너', linkMedia: '미디어', linkNews: '최신 소식', linkGallery: '갤러리', linkContact: '문의', legalLabel: '등록 정보', dateLocation: '2026년 6월 13–14일 · 그단스크', copyright: 'CERBERUS K9 © 2026. 모든 권리 보유 · Sebastian Bożek.' },
};
