import type { Lang } from './utils';

export type LocationItem = {
	name: string;
	description: string;
	detail: string;
};

export type LocationsSectionCopy = {
	sectionTag: string;
	sectionTitle: string;
	statusConfirmed: string;
	locations: [LocationItem, LocationItem, LocationItem, LocationItem];
};

const plLocations: [LocationItem, LocationItem, LocationItem, LocationItem] = [
	{ name: '3MK ARENA', description: 'Główna arena zawodów K9 i pokazów dynamicznych dla służb oraz publiczności.', detail: 'ul. Traugutta, Gdańsk' },
	{ name: 'SZKOŁA MUNDUROWA', description: 'Szkolenia taktyczne TCCC oraz moduły medycyny pola walki dla operatorów.', detail: 'Gdańsk' },
	{ name: 'STADION MIEJSKI', description: 'Drony bojowe i demonstracje UAV z elementami rozpoznania i wsparcia.', detail: 'Gdańsk' },
	{ name: 'STENA LINE TERMINAL', description: 'Ceremonia otwarcia i gala z udziałem delegacji międzynarodowych.', detail: 'Port Gdańsk' },
];

const enLocations: [LocationItem, LocationItem, LocationItem, LocationItem] = [
	{ name: '3MK ARENA', description: 'Main K9 competition arena and dynamic demonstrations for services and the public.', detail: 'Traugutta Street, Gdańsk' },
	{ name: 'UNIFORMED SERVICES SCHOOL', description: 'Tactical TCCC training and combat-medicine modules for operators.', detail: 'Gdańsk' },
	{ name: 'CITY STADIUM', description: 'Combat drone and UAV demonstrations with reconnaissance support workflows.', detail: 'Gdańsk' },
	{ name: 'STENA LINE TERMINAL', description: 'Opening ceremony and gala attended by international delegations.', detail: 'Port of Gdańsk' },
];

export const locationsSectionByLang: Record<Lang, LocationsSectionCopy> = {
	pl: { sectionTag: 'LOKALIZACJE', sectionTitle: 'INFRASTRUKTURA EVENTU', statusConfirmed: 'POTWIERDZONE', locations: plLocations },
	en: { sectionTag: 'LOCATIONS', sectionTitle: 'EVENT INFRASTRUCTURE', statusConfirmed: 'CONFIRMED', locations: enLocations },
	de: { sectionTag: 'STANDORTE', sectionTitle: 'EVENT-INFRASTRUKTUR', statusConfirmed: 'BESTÄTIGT', locations: [{ name: '3MK ARENA', description: 'Hauptarena für K9-Wettkämpfe und dynamische Vorführungen für Dienste und Publikum.', detail: 'Traugutta-Straße, Danzig' }, { name: 'UNIFORMSCHULE', description: 'Taktische TCCC-Schulung und Module der Gefechtsmedizin für Einsatzkräfte.', detail: 'Danzig' }, { name: 'STADION', description: 'Kampf- und Aufklärungsdrohnen mit UAV-Demonstrationen und Einsatzszenarien.', detail: 'Danzig' }, { name: 'STENA LINE TERMINAL', description: 'Eröffnungszeremonie und Gala mit internationalen Delegationen.', detail: 'Hafen Danzig' }] },
	fr: { sectionTag: 'LIEUX', sectionTitle: "INFRASTRUCTURE DE L'ÉVÉNEMENT", statusConfirmed: 'CONFIRMÉ', locations: [{ name: '3MK ARENA', description: 'Arène principale des compétitions K9 et démonstrations dynamiques pour services et public.', detail: 'Rue Traugutta, Gdańsk' }, { name: 'ÉCOLE EN UNIFORME', description: 'Formations tactiques TCCC et modules de médecine de combat pour opérateurs.', detail: 'Gdańsk' }, { name: 'STADE MUNICIPAL', description: 'Drones de combat et démonstrations UAV avec éléments de reconnaissance.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: "Cérémonie d'ouverture et gala avec délégations internationales.", detail: 'Port de Gdańsk' }] },
	hr: { sectionTag: 'LOKACIJE', sectionTitle: 'INFRASTRUKTURA DOGAĐAJA', statusConfirmed: 'POTVRĐENO', locations: [{ name: '3MK ARENA', description: 'Glavna arena K9 natjecanja i dinamičnih demonstracija za službe i publiku.', detail: 'ul. Traugutta, Gdańsk' }, { name: 'ŠKOLA MUNDUROWA', description: 'Taktička TCCC obuka i borbena medicina za operatere.', detail: 'Gdańsk' }, { name: 'GRADSKI STADION', description: 'Borbeni dronovi i UAV demonstracije s elementima izviđanja.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Ceremonija otvaranja i gala uz međunarodne delegacije.', detail: 'Luka Gdańsk' }] },
	cs: { sectionTag: 'LOKACE', sectionTitle: 'INFRASTRUKTURA AKCE', statusConfirmed: 'POTVRZENO', locations: [{ name: '3MK ARENA', description: 'Hlavní aréna soutěží K9 a dynamických ukázek pro složky i veřejnost.', detail: 'ul. Traugutta, Gdańsk' }, { name: 'ŠKOLA V UNIFORMĚ', description: 'Taktický výcvik TCCC a moduly bojové medicíny pro operátory.', detail: 'Gdańsk' }, { name: 'MĚSTSKÝ STADION', description: 'Bojové drony a ukázky UAV včetně průzkumných scénářů.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Zahajovací ceremoniál a gala s mezinárodními delegacemi.', detail: 'Přístav Gdańsk' }] },
	lt: { sectionTag: 'VIETOS', sectionTitle: 'RENGINIO INFRASTRUKTŪRA', statusConfirmed: 'PATVIRTINTA', locations: [{ name: '3MK ARENA', description: 'Pagrindinė K9 varžybų arena ir dinaminiai pasirodymai tarnyboms bei žiūrovams.', detail: 'Traugutta g., Gdanskas' }, { name: 'MUNDUROWA MOKYKLA', description: 'Taktiniai TCCC mokymai ir kovinės medicinos moduliai operatoriams.', detail: 'Gdanskas' }, { name: 'MIESTO STADIONAS', description: 'Koviniai dronai ir UAV demonstracijos su žvalgybos elementais.', detail: 'Gdanskas' }, { name: 'STENA LINE TERMINAL', description: 'Atidarymo ceremonija ir gala su tarptautinėmis delegacijomis.', detail: 'Gdansko uostas' }] },
	lv: { sectionTag: 'LOKĀCIJAS', sectionTitle: 'PASĀKUMA INFRASTRUKTŪRA', statusConfirmed: 'APSTIPRINĀTS', locations: [{ name: '3MK ARENA', description: 'Galvenā K9 sacensību arēna un dinamiskas demonstrācijas dienestiem un skatītājiem.', detail: 'Traugutta iela, Gdaņska' }, { name: 'MUNDUROWA SKOLA', description: 'Taktiskās TCCC apmācības un kaujas medicīnas moduļi operatoriem.', detail: 'Gdaņska' }, { name: 'PILSĒTAS STADIONS', description: 'Kaujas droni un UAV demonstrācijas ar izlūkošanas elementiem.', detail: 'Gdaņska' }, { name: 'STENA LINE TERMINAL', description: 'Atklāšanas ceremonija un gala ar starptautiskām delegācijām.', detail: 'Gdaņskas osta' }] },
	sk: { sectionTag: 'LOKALITY', sectionTitle: 'INFRAŠTRUKTÚRA PODUJATIA', statusConfirmed: 'POTVRDENÉ', locations: [{ name: '3MK ARENA', description: 'Hlavná aréna súťaží K9 a dynamických ukážok pre zložky aj verejnosť.', detail: 'ul. Traugutta, Gdańsk' }, { name: 'ŠKOLA V UNIFORME', description: 'Taktické školenia TCCC a bojová medicína pre operátorov.', detail: 'Gdańsk' }, { name: 'MESTSKÝ ŠTADIÓN', description: 'Bojové drony a UAV demonštrácie s prvkami prieskumu.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Otvárací ceremoniál a gala za účasti medzinárodných delegácií.', detail: 'Prístav Gdańsk' }] },
	sl: { sectionTag: 'LOKACIJE', sectionTitle: 'INFRASTRUKTURA DOGODKA', statusConfirmed: 'POTRJENO', locations: [{ name: '3MK ARENA', description: 'Glavna arena K9 tekmovanj in dinamičnih prikazov za službe in javnost.', detail: 'ul. Traugutta, Gdańsk' }, { name: 'MUNDUROWA ŠOLA', description: 'Taktično usposabljanje TCCC in moduli bojne medicine za operaterje.', detail: 'Gdańsk' }, { name: 'MESTNI STADION', description: 'Bojni droni in UAV demonstracije z izvidniškimi elementi.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Otvoritvena slovesnost in gala z mednarodnimi delegacijami.', detail: 'Pristanišče Gdańsk' }] },
	hu: { sectionTag: 'HELYSZÍNEK', sectionTitle: 'AZ ESEMÉNY INFRASTRUKTÚRÁJA', statusConfirmed: 'MEGERŐSÍTVE', locations: [{ name: '3MK ARENA', description: 'A K9 versenyek fő arénája és dinamikus bemutatók a szolgálatok és a közönség számára.', detail: 'Traugutta utca, Gdańsk' }, { name: 'EGYENRUHÁS ISKOLA', description: 'Taktikai TCCC-képzés és harctéri orvoslási modulok operátoroknak.', detail: 'Gdańsk' }, { name: 'VÁROSI STADION', description: 'Harci drónok és UAV-demonstrációk felderítési elemekkel.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Megnyitó ceremónia és gála nemzetközi delegációkkal.', detail: 'Gdański kikötő' }] },
	no: { sectionTag: 'LOKASJONER', sectionTitle: 'ARRANGEMENTETS INFRASTRUKTUR', statusConfirmed: 'BEKREFTET', locations: [{ name: '3MK ARENA', description: 'Hovedarena for K9-konkurranser og dynamiske demonstrasjoner for tjenester og publikum.', detail: 'Traugutta-gaten, Gdańsk' }, { name: 'UNIFORMSSKOLE', description: 'Taktisk TCCC-trening og feltmedisinske moduler for operatører.', detail: 'Gdańsk' }, { name: 'BYSTADION', description: 'Kampdroner og UAV-demonstrasjoner med rekognoseringsinnhold.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Åpningsseremoni og galla med internasjonale delegasjoner.', detail: 'Gdańsk havn' }] },
	sv: { sectionTag: 'PLATSER', sectionTitle: 'EVENTINFRASTRUKTUR', statusConfirmed: 'BEKRÄFTAT', locations: [{ name: '3MK ARENA', description: 'Huvudarena för K9-tävlingar och dynamiska uppvisningar för myndigheter och publik.', detail: 'Traugutta-gatan, Gdańsk' }, { name: 'UNIFORMSSKOLA', description: 'Taktisk TCCC-utbildning och stridsmedicinska moduler för operatörer.', detail: 'Gdańsk' }, { name: 'STADION', description: 'Stridsdrönare och UAV-demonstrationer med spaningsmoment.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Öppningsceremoni och gala med internationella delegationer.', detail: 'Gdańsks hamn' }] },
	nl: { sectionTag: 'LOCATIES', sectionTitle: 'EVENTINFRASTRUCTUUR', statusConfirmed: 'BEVESTIGD', locations: [{ name: '3MK ARENA', description: 'Hoofdarena voor K9-wedstrijden en dynamische demonstraties voor diensten en publiek.', detail: 'Traugutta-straat, Gdańsk' }, { name: 'UNIFORMSCHOOL', description: 'Tactische TCCC-training en gevechtsmedische modules voor operators.', detail: 'Gdańsk' }, { name: 'STADION', description: 'Gevechtsdrones en UAV-demonstraties met verkenningsonderdelen.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Openingsceremonie en gala met internationale delegaties.', detail: 'Haven van Gdańsk' }] },
	es: { sectionTag: 'UBICACIONES', sectionTitle: 'INFRAESTRUCTURA DEL EVENTO', statusConfirmed: 'CONFIRMADO', locations: [{ name: '3MK ARENA', description: 'Arena principal de competiciones K9 y demostraciones dinámicas para servicios y público.', detail: 'Calle Traugutta, Gdańsk' }, { name: 'ESCUELA UNIFORMADA', description: 'Formación táctica TCCC y módulos de medicina de combate para operadores.', detail: 'Gdańsk' }, { name: 'ESTADIO MUNICIPAL', description: 'Drones de combate y demostraciones UAV con componentes de reconocimiento.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Ceremonia de apertura y gala con delegaciones internacionales.', detail: 'Puerto de Gdańsk' }] },
	pt: { sectionTag: 'LOCAIS', sectionTitle: 'INFRAESTRUTURA DO EVENTO', statusConfirmed: 'CONFIRMADO', locations: [{ name: '3MK ARENA', description: 'Arena principal das competições K9 e demonstrações dinâmicas para serviços e público.', detail: 'Rua Traugutta, Gdańsk' }, { name: 'ESCOLA FARDADA', description: 'Formação tática TCCC e módulos de medicina de combate para operadores.', detail: 'Gdańsk' }, { name: 'ESTÁDIO MUNICIPAL', description: 'Drones de combate e demonstrações UAV com componente de reconhecimento.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Cerimónia de abertura e gala com delegações internacionais.', detail: 'Porto de Gdańsk' }] },
	ro: { sectionTag: 'LOCAȚII', sectionTitle: 'INFRASTRUCTURA EVENIMENTULUI', statusConfirmed: 'CONFIRMAT', locations: [{ name: '3MK ARENA', description: 'Arena principală pentru competițiile K9 și demonstrații dinamice pentru structuri și public.', detail: 'Str. Traugutta, Gdańsk' }, { name: 'ȘCOALA ÎN UNIFORMĂ', description: 'Instruire tactică TCCC și module de medicină de luptă pentru operatori.', detail: 'Gdańsk' }, { name: 'STADIONUL ORAȘULUI', description: 'Drone de luptă și demonstrații UAV cu elemente de recunoaștere.', detail: 'Gdańsk' }, { name: 'STENA LINE TERMINAL', description: 'Ceremonia de deschidere și gala cu delegații internaționale.', detail: 'Portul Gdańsk' }] },
	it: { sectionTag: 'LOCALITÀ', sectionTitle: "INFRASTRUTTURA DELL'EVENTO", statusConfirmed: 'CONFERMATO', locations: [{ name: '3MK ARENA', description: 'Arena principale delle competizioni K9 e dimostrazioni dinamiche per servizi e pubblico.', detail: 'Via Traugutta, Danzica' }, { name: 'SCUOLA IN DIVISA', description: 'Formazione tattica TCCC e moduli di medicina operativa per operatori.', detail: 'Danzica' }, { name: 'STADIO COMUNALE', description: 'Droni da combattimento e dimostrazioni UAV con elementi di ricognizione.', detail: 'Danzica' }, { name: 'STENA LINE TERMINAL', description: 'Cerimonia di apertura e gala con delegazioni internazionali.', detail: 'Porto di Danzica' }] },
	ko: { sectionTag: '장소', sectionTitle: '이벤트 인프라', statusConfirmed: '확정', locations: [{ name: '3MK ARENA', description: 'K9 대회와 역동적 시연이 진행되는 메인 경기장입니다.', detail: '트라우구타 거리, 그단스크' }, { name: '제복학교', description: '운용 요원을 위한 TCCC 전술 훈련 및 전장 의무 모듈.', detail: '그단스크' }, { name: '시립 스타디움', description: '전투 드론과 UAV 시연, 정찰 운용 시나리오를 포함합니다.', detail: '그단스크' }, { name: 'STENA LINE TERMINAL', description: '국제 대표단이 참여하는 개막식 및 갈라 행사 장소입니다.', detail: '그단스크 항구' }] },
};
