import type { Lang } from './utils';
import type { ProgramCard } from '../lib/homepageCards';

export type { ProgramCard } from '../lib/homepageCards';

export type ProgramSectionCopy = {
	sectionTag: string;
	sectionTitle: string;
	cards: [ProgramCard, ProgramCard, ProgramCard, ProgramCard, ProgramCard];
};

const plCards: [ProgramCard, ProgramCard, ProgramCard, ProgramCard, ProgramCard] = [
	{ badge: 'DZIEŃ 1-2', category: 'K9 COMBAT', title: 'Szkolenia K9', description: 'Intensywne zajęcia z psami bojowymi NATO, taktyką zespołów i pracą w środowisku wysokiego ryzyka.' },
	{ badge: 'DZIEŃ 1', category: 'TCCC', title: 'Taktyczna Opieka', description: 'Combat Lifesaver i TCCC dla operatorów: procedury MARCH, ewakuacja i medycyna pola walki.' },
	{ badge: 'DZIEŃ 1-2', category: 'DRONY', title: 'Systemy UAV', description: 'Drony bojowe, rozpoznawcze i FPV: planowanie misji, obserwacja i wsparcie działań służb.' },
	{ badge: 'DZIEŃ 2', category: 'KONFERENCJA', title: 'Bezpieczeństwo', description: 'Konferencja dla służb mundurowych powiatów: wymiana doświadczeń i procedury reagowania kryzysowego.' },
	{ badge: 'DZIEŃ 2', category: 'HARDEST HIT', title: 'Zawody K9', description: 'Elitarne zawody psów bojowych o Puchar Dyrektora z realistycznymi scenariuszami operacyjnymi.' },
];

const enCards: [ProgramCard, ProgramCard, ProgramCard, ProgramCard, ProgramCard] = [
	{ badge: 'DAY 1-2', category: 'K9 COMBAT', title: 'K9 Training', description: 'Intensive NATO working-dog modules focused on team tactics and high-threat operational environments.' },
	{ badge: 'DAY 1', category: 'TCCC', title: 'Tactical Care', description: 'Combat Lifesaver and TCCC training for operators, including MARCH procedures and casualty evacuation.' },
	{ badge: 'DAY 1-2', category: 'DRONES', title: 'UAV Systems', description: 'Combat, reconnaissance, and FPV drone modules covering mission planning and field deployment.' },
	{ badge: 'DAY 2', category: 'CONFERENCE', title: 'Security', description: 'Security conference for uniformed services focused on interagency coordination and crisis response.' },
	{ badge: 'DAY 2', category: 'HARDEST HIT', title: 'K9 Competition', description: 'Elite combat-dog competition for the Director’s Cup under realistic tactical scenarios.' },
];

export const programSectionByLang: Record<Lang, ProgramSectionCopy> = {
	pl: { sectionTag: 'PROGRAM GŁÓWNY', sectionTitle: 'CO CIĘ CZEKA', cards: plCards },
	en: { sectionTag: 'MAIN PROGRAM', sectionTitle: 'WHAT AWAITS YOU', cards: enCards },
	de: { sectionTag: 'HAUPTPROGRAMM', sectionTitle: 'WAS SIE ERWARTET', cards: [{ badge: 'TAG 1-2', category: 'K9 COMBAT', title: 'K9-Training', description: 'Intensive Ausbildung mit NATO-Diensthunden, Teamtaktik und Einsätzen in Hochrisikoumgebungen.' }, { badge: 'TAG 1', category: 'TCCC', title: 'Taktische Versorgung', description: 'Combat Lifesaver und TCCC für Einsatzkräfte mit MARCH-Schema und Verwundetenevakuierung.' }, { badge: 'TAG 1-2', category: 'DROHNEN', title: 'UAV-Systeme', description: 'Kampf-, Aufklärungs- und FPV-Drohnen: Missionsplanung, Aufklärung und operative Unterstützung.' }, { badge: 'TAG 2', category: 'KONFERENZ', title: 'Sicherheit', description: 'Konferenz für uniformierte Dienste zu Krisenreaktion und behördenübergreifender Zusammenarbeit.' }, { badge: 'TAG 2', category: 'HARDEST HIT', title: 'K9-Wettkampf', description: 'Elite-Wettkampf von Diensthunden um den Direktorenpokal in realistischen Szenarien.' }] },
	fr: { sectionTag: 'PROGRAMME PRINCIPAL', sectionTitle: 'CE QUI VOUS ATTEND', cards: [{ badge: 'JOUR 1-2', category: 'K9 COMBAT', title: 'Formations K9', description: 'Sessions intensives avec chiens de combat OTAN, tactiques d’équipe et environnement à haut risque.' }, { badge: 'JOUR 1', category: 'TCCC', title: 'Soins tactiques', description: 'Combat Lifesaver et TCCC pour opérateurs: protocole MARCH, évacuation et médecine de combat.' }, { badge: 'JOUR 1-2', category: 'DRONES', title: 'Systèmes UAV', description: 'Drones de combat, de reconnaissance et FPV: planification de mission et déploiement terrain.' }, { badge: 'JOUR 2', category: 'CONFÉRENCE', title: 'Sécurité', description: 'Conférence pour services en uniforme sur la coordination interservices et la gestion de crise.' }, { badge: 'JOUR 2', category: 'HARDEST HIT', title: 'Compétition K9', description: 'Compétition élite de chiens opérationnels pour la Coupe du Directeur, en scénarios réalistes.' }] },
	hr: { sectionTag: 'GLAVNI PROGRAM', sectionTitle: 'ŠTO VAS OČEKUJE', cards: [{ badge: 'DAN 1-2', category: 'K9 COMBAT', title: 'K9 obuka', description: 'Intenzivna obuka s NATO borbenim psima, timska taktika i rad u uvjetima visokog rizika.' }, { badge: 'DAN 1', category: 'TCCC', title: 'Taktička skrb', description: 'Combat Lifesaver i TCCC za operatere: MARCH postupci, evakuacija i borbena medicina.' }, { badge: 'DAN 1-2', category: 'DRONOVI', title: 'UAV sustavi', description: 'Borbeni, izviđački i FPV dronovi: planiranje misija i operativna podrška.' }, { badge: 'DAN 2', category: 'KONFERENCIJA', title: 'Sigurnost', description: 'Konferencija za službe o koordinaciji i kriznom odgovoru.' }, { badge: 'DAN 2', category: 'HARDEST HIT', title: 'K9 natjecanje', description: 'Elitno natjecanje borbenih pasa za Kup ravnatelja u realnim scenarijima.' }] },
	cs: { sectionTag: 'HLAVNÍ PROGRAM', sectionTitle: 'CO VÁS ČEKÁ', cards: [{ badge: 'DEN 1-2', category: 'K9 COMBAT', title: 'Výcvik K9', description: 'Intenzivní výcvik NATO služebních psů, týmová taktika a operace ve vysokém riziku.' }, { badge: 'DEN 1', category: 'TCCC', title: 'Taktická péče', description: 'Combat Lifesaver a TCCC pro operátory: MARCH, evakuace a bojová medicína.' }, { badge: 'DEN 1-2', category: 'DRONY', title: 'Systémy UAV', description: 'Bojové, průzkumné a FPV drony: plánování mise a nasazení v terénu.' }, { badge: 'DEN 2', category: 'KONFERENCE', title: 'Bezpečnost', description: 'Konference pro uniformované složky o krizové reakci a spolupráci.' }, { badge: 'DEN 2', category: 'HARDEST HIT', title: 'Soutěž K9', description: 'Elitní soutěž služebních psů o pohár ředitele v realistických scénářích.' }] },
	lt: { sectionTag: 'PAGRINDINĖ PROGRAMA', sectionTitle: 'KAS JŪSŲ LAUKIA', cards: [{ badge: '1-2 DIENA', category: 'K9 COMBAT', title: 'K9 mokymai', description: 'Intensyvūs NATO kovinių šunų mokymai, komandinė taktika ir aukštos rizikos aplinka.' }, { badge: '1 DIENA', category: 'TCCC', title: 'Taktinė priežiūra', description: 'Combat Lifesaver ir TCCC operatoriams: MARCH protokolas, evakuacija ir kovos medicina.' }, { badge: '1-2 DIENA', category: 'DRONAI', title: 'UAV sistemos', description: 'Koviniai, žvalgybiniai ir FPV dronai: misijų planavimas ir palaikymas.' }, { badge: '2 DIENA', category: 'KONFERENCIJA', title: 'Saugumas', description: 'Konferencija uniformuotoms tarnyboms apie krizines procedūras ir koordinavimą.' }, { badge: '2 DIENA', category: 'HARDEST HIT', title: 'K9 varžybos', description: 'Elitinės kovinių šunų varžybos dėl Direktoriaus taurės realistiškuose scenarijuose.' }] },
	lv: { sectionTag: 'GALVENĀ PROGRAMMA', sectionTitle: 'KAS JŪS SAGAIDA', cards: [{ badge: '1.-2. DIENA', category: 'K9 COMBAT', title: 'K9 apmācība', description: 'Intensīvas NATO dienesta suņu nodarbības, komandu taktika un augsta riska vide.' }, { badge: '1. DIENA', category: 'TCCC', title: 'Taktiskā aprūpe', description: 'Combat Lifesaver un TCCC operatoriem: MARCH procedūras, evakuācija un kaujas medicīna.' }, { badge: '1.-2. DIENA', category: 'DRONI', title: 'UAV sistēmas', description: 'Kaujas, izlūkošanas un FPV droni: misiju plānošana un operatīvais atbalsts.' }, { badge: '2. DIENA', category: 'KONFERENCE', title: 'Drošība', description: 'Konference dienestiem par krīžu vadību un starpinstitūciju sadarbību.' }, { badge: '2. DIENA', category: 'HARDEST HIT', title: 'K9 sacensības', description: 'Elites dienesta suņu sacensības par direktora kausu reālistiskos scenārijos.' }] },
	sk: { sectionTag: 'HLAVNÝ PROGRAM', sectionTitle: 'ČO VÁS ČAKÁ', cards: [{ badge: 'DEŇ 1-2', category: 'K9 COMBAT', title: 'Výcvik K9', description: 'Intenzívny výcvik NATO služobných psov, tímová taktika a operácie vo vysokom riziku.' }, { badge: 'DEŇ 1', category: 'TCCC', title: 'Taktická starostlivosť', description: 'Combat Lifesaver a TCCC pre operátorov: MARCH, evakuácia a bojová medicína.' }, { badge: 'DEŇ 1-2', category: 'DRONY', title: 'UAV systémy', description: 'Bojové, prieskumné a FPV drony: plánovanie misií a podpora zásahov.' }, { badge: 'DEŇ 2', category: 'KONFERENCIA', title: 'Bezpečnosť', description: 'Konferencia pre ozbrojené zložky o koordinácii a krízovej reakcii.' }, { badge: 'DEŇ 2', category: 'HARDEST HIT', title: 'K9 súťaž', description: 'Elitná súťaž služobných psov o pohár riaditeľa v realistických scenároch.' }] },
	sl: { sectionTag: 'GLAVNI PROGRAM', sectionTitle: 'KAJ VAS ČAKA', cards: [{ badge: 'DAN 1-2', category: 'K9 COMBAT', title: 'K9 usposabljanje', description: 'Intenzivno usposabljanje z NATO službenimi psi, ekipna taktika in visoko rizično okolje.' }, { badge: 'DAN 1', category: 'TCCC', title: 'Taktična oskrba', description: 'Combat Lifesaver in TCCC za operaterje: MARCH postopki, evakuacija in bojna medicina.' }, { badge: 'DAN 1-2', category: 'DRONI', title: 'UAV sistemi', description: 'Bojni, izvidniški in FPV droni: načrtovanje misij in terenska podpora.' }, { badge: 'DAN 2', category: 'KONFERENCA', title: 'Varnost', description: 'Konferenca za uniformirane službe o kriznem odzivu in sodelovanju.' }, { badge: 'DAN 2', category: 'HARDEST HIT', title: 'K9 tekmovanje', description: 'Elitno tekmovanje službenih psov za pokal direktorja v realističnih scenarijih.' }] },
	hu: { sectionTag: 'FŐ PROGRAM', sectionTitle: 'AMI ÖNRE VÁR', cards: [{ badge: '1-2. NAP', category: 'K9 COMBAT', title: 'K9 képzés', description: 'Intenzív NATO szolgálati kutya képzés, csapattaktika és magas kockázatú környezet.' }, { badge: '1. NAP', category: 'TCCC', title: 'Taktikai ellátás', description: 'Combat Lifesaver és TCCC operátoroknak: MARCH-protokoll, evakuálás és harctéri medicina.' }, { badge: '1-2. NAP', category: 'DRÓNOK', title: 'UAV rendszerek', description: 'Harci, felderítő és FPV drónok: missziótervezés és műveleti támogatás.' }, { badge: '2. NAP', category: 'KONFERENCIA', title: 'Biztonság', description: 'Konferencia egyenruhás szolgálatoknak válságkezelésről és együttműködésről.' }, { badge: '2. NAP', category: 'HARDEST HIT', title: 'K9 verseny', description: 'Elit harci kutyás verseny az Igazgatói Kupáért realisztikus helyzetekben.' }] },
	no: { sectionTag: 'HOVEDPROGRAM', sectionTitle: 'DETTE VENTER DEG', cards: [{ badge: 'DAG 1-2', category: 'K9 COMBAT', title: 'K9-trening', description: 'Intensiv trening med NATO-tjenestehunder, lagtaktikk og arbeid i høyrisikomiljø.' }, { badge: 'DAG 1', category: 'TCCC', title: 'Taktisk pleie', description: 'Combat Lifesaver og TCCC for operatører: MARCH-prosedyrer, evakuering og feltmedisin.' }, { badge: 'DAG 1-2', category: 'DRONER', title: 'UAV-systemer', description: 'Kamp-, rekognoserings- og FPV-droner: oppdragsplanlegging og operativ støtte.' }, { badge: 'DAG 2', category: 'KONFERANSE', title: 'Sikkerhet', description: 'Konferanse for uniformerte tjenester om krisehåndtering og samvirke.' }, { badge: 'DAG 2', category: 'HARDEST HIT', title: 'K9-konkurranse', description: 'Elitekonkurranse for tjenestehunder om Direktørens pokal i realistiske scenarioer.' }] },
	sv: { sectionTag: 'HUVUDPROGRAM', sectionTitle: 'DETTA VÄNTAR DIG', cards: [{ badge: 'DAG 1-2', category: 'K9 COMBAT', title: 'K9-utbildning', description: 'Intensiv utbildning med NATO-tjänstehundar, lagtaktik och hög-riskmiljö.' }, { badge: 'DAG 1', category: 'TCCC', title: 'Taktisk vård', description: 'Combat Lifesaver och TCCC för operatörer: MARCH, evakuering och stridsmedicin.' }, { badge: 'DAG 1-2', category: 'DRÖNARE', title: 'UAV-system', description: 'Strids-, spanings- och FPV-drönare: uppdragsplanering och operativt stöd.' }, { badge: 'DAG 2', category: 'KONFERENS', title: 'Säkerhet', description: 'Konferens för uniformerade tjänster om krisrespons och samordning.' }, { badge: 'DAG 2', category: 'HARDEST HIT', title: 'K9-tävling', description: 'Elittävling för tjänstehundar om Direktörens Cup i realistiska scenarier.' }] },
	nl: { sectionTag: 'HOOFDPROGRAMMA', sectionTitle: 'WAT JE TE WACHTEN STAAT', cards: [{ badge: 'DAG 1-2', category: 'K9 COMBAT', title: 'K9-training', description: 'Intensieve training met NAVO-diensthonden, teamtactiek en hoogrisico-operaties.' }, { badge: 'DAG 1', category: 'TCCC', title: 'Tactische zorg', description: 'Combat Lifesaver en TCCC voor operators: MARCH-procedures, evacuatie en gevechtsgeneeskunde.' }, { badge: 'DAG 1-2', category: 'DRONES', title: 'UAV-systemen', description: 'Gevechts-, verkennings- en FPV-drones: missieplanning en operationele inzet.' }, { badge: 'DAG 2', category: 'CONFERENTIE', title: 'Veiligheid', description: 'Conferentie voor uniformdiensten over crisisrespons en interdisciplinaire coördinatie.' }, { badge: 'DAG 2', category: 'HARDEST HIT', title: 'K9-wedstrijd', description: 'Elitewedstrijd van diensthonden om de beker van de directeur in realistische scenario’s.' }] },
	es: { sectionTag: 'PROGRAMA PRINCIPAL', sectionTitle: 'LO QUE TE ESPERA', cards: [{ badge: 'DÍA 1-2', category: 'K9 COMBAT', title: 'Entrenamiento K9', description: 'Módulos intensivos con perros operativos OTAN, táctica de equipos y entorno de alto riesgo.' }, { badge: 'DÍA 1', category: 'TCCC', title: 'Atención táctica', description: 'Combat Lifesaver y TCCC para operadores: protocolo MARCH, evacuación y medicina de combate.' }, { badge: 'DÍA 1-2', category: 'DRONES', title: 'Sistemas UAV', description: 'Drones de combate, reconocimiento y FPV: planificación de misión y apoyo operativo.' }, { badge: 'DÍA 2', category: 'CONFERENCIA', title: 'Seguridad', description: 'Conferencia para servicios uniformados sobre coordinación y respuesta ante crisis.' }, { badge: 'DÍA 2', category: 'HARDEST HIT', title: 'Competición K9', description: 'Competición élite de perros operativos por la Copa del Director en escenarios realistas.' }] },
	pt: { sectionTag: 'PROGRAMA PRINCIPAL', sectionTitle: 'O QUE O ESPERA', cards: [{ badge: 'DIA 1-2', category: 'K9 COMBAT', title: 'Formação K9', description: 'Treino intensivo com cães operacionais NATO, tática de equipa e ambiente de alto risco.' }, { badge: 'DIA 1', category: 'TCCC', title: 'Cuidados táticos', description: 'Combat Lifesaver e TCCC para operadores: protocolo MARCH, evacuação e medicina de combate.' }, { badge: 'DIA 1-2', category: 'DRONES', title: 'Sistemas UAV', description: 'Drones de combate, reconhecimento e FPV: planeamento de missão e apoio operacional.' }, { badge: 'DIA 2', category: 'CONFERÊNCIA', title: 'Segurança', description: 'Conferência para serviços fardados sobre coordenação e resposta a crises.' }, { badge: 'DIA 2', category: 'HARDEST HIT', title: 'Competição K9', description: 'Competição de elite de cães operacionais pela Taça do Diretor em cenários realistas.' }] },
	ro: { sectionTag: 'PROGRAM PRINCIPAL', sectionTitle: 'CE TE AȘTEAPTĂ', cards: [{ badge: 'ZIUA 1-2', category: 'K9 COMBAT', title: 'Instruire K9', description: 'Module intensive cu câini de luptă NATO, tactică de echipă și medii cu risc ridicat.' }, { badge: 'ZIUA 1', category: 'TCCC', title: 'Îngrijire tactică', description: 'Combat Lifesaver și TCCC pentru operatori: protocol MARCH, evacuare și medicină de luptă.' }, { badge: 'ZIUA 1-2', category: 'DRONE', title: 'Sisteme UAV', description: 'Drone de luptă, recunoaștere și FPV: planificare de misiune și sprijin operațional.' }, { badge: 'ZIUA 2', category: 'CONFERINȚĂ', title: 'Securitate', description: 'Conferință pentru structuri în uniformă privind cooperarea și răspunsul la crize.' }, { badge: 'ZIUA 2', category: 'HARDEST HIT', title: 'Competiție K9', description: 'Competiție de elită a câinilor de serviciu pentru Cupa Directorului, în scenarii realiste.' }] },
	it: { sectionTag: 'PROGRAMMA PRINCIPALE', sectionTitle: 'COSA TI ASPETTA', cards: [{ badge: 'GIORNO 1-2', category: 'K9 COMBAT', title: 'Addestramento K9', description: 'Sessioni intensive con cani operativi NATO, tattiche di squadra e ambienti ad alto rischio.' }, { badge: 'GIORNO 1', category: 'TCCC', title: 'Assistenza tattica', description: 'Combat Lifesaver e TCCC per operatori: protocollo MARCH, evacuazione e medicina operativa.' }, { badge: 'GIORNO 1-2', category: 'DRONI', title: 'Sistemi UAV', description: 'Droni da combattimento, ricognizione e FPV: pianificazione missione e supporto sul campo.' }, { badge: 'GIORNO 2', category: 'CONFERENZA', title: 'Sicurezza', description: 'Conferenza per servizi in uniforme su coordinamento interforze e risposta alle crisi.' }, { badge: 'GIORNO 2', category: 'HARDEST HIT', title: 'Competizione K9', description: 'Competizione élite di cani operativi per la Coppa del Direttore in scenari realistici.' }] },
	ko: { sectionTag: '메인 프로그램', sectionTitle: '참가자를 기다리는 것', cards: [{ badge: '1-2일차', category: 'K9 COMBAT', title: 'K9 훈련', description: 'NATO 전투견 중심의 집중 훈련으로 팀 전술과 고위험 환경 대응을 다룹니다.' }, { badge: '1일차', category: 'TCCC', title: '전술 응급처치', description: '운용 요원을 위한 Combat Lifesaver 및 TCCC, MARCH 절차와 후송 훈련.' }, { badge: '1-2일차', category: '드론', title: 'UAV 시스템', description: '전투·정찰·FPV 드론 운용: 임무 계획, 관측, 현장 지원.' }, { badge: '2일차', category: '컨퍼런스', title: '안보', description: '제복 기관 대상 위기 대응 및 기관 간 협력 컨퍼런스.' }, { badge: '2일차', category: 'HARDEST HIT', title: 'K9 대회', description: '실전형 시나리오로 진행되는 디렉터 컵 엘리트 전투견 대회.' }] },
};
